### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by elpinnen** [Microsoft/emat#3]
It seem that mail address with / in personal part make program to crash. I've tested 3 times on 2 Machines but it stops at same Place.

Edit: It seems to be something else bacuse changing address to - instead of / doesn't made any difference

[trace.zip](https://github.com/Microsoft/emat/files/1120277/trace.zip)

**Comment by reikor0x** [comment]
Export Tool (.exe) is still under development. Use the powershell script instead that works for sure.

Just for debugging purpose can you please also send the exception running the tool from a command prompt?

Thanks

**Comment by elpinnen** [comment]
From Event Viewer:

Log Name:      Application
Source:        Windows Error Reporting
Date:          13.07.2017 11:13:28
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      dgi-admkli-11.AD.DGI.NO
Description:
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: ExportPermissionsTool.exe
P2: 1.0.0.0
P3: 586e36ef
P4: System.DirectoryServices
P5: 4.0.30319.36366
P6: 57a0fa90
P7: 8e
P8: 18
P9: PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX
P10:

Attached files:

These files may be available here:
C:\Users\thostr\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_ExportPermission_286fd375f1e97db845414425ca7bcb84d9137c96_dda2c22b_09154b2f

Analysis symbol:
Rechecking for solution: 0
Report Id: 67dd7b44-67ab-11e7-832f-0050568a6e8b
Report Status: 2048
Hashed bucket:
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-07-13T09:13:28.000000000Z" />
    <EventRecordID>23982</EventRecordID>
    <Channel>Application</Channel>
    <Computer>dgi-admkli-11.AD.DGI.NO</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>CLR20r3</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>ExportPermissionsTool.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>586e36ef</Data>
    <Data>System.DirectoryServices</Data>
    <Data>4.0.30319.36366</Data>
    <Data>57a0fa90</Data>
    <Data>8e</Data>
    <Data>18</Data>
    <Data>PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>C:\Users\thostr\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_ExportPermission_286fd375f1e97db845414425ca7bcb84d9137c96_dda2c22b_09154b2f</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>67dd7b44-67ab-11e7-832f-0050568a6e8b</Data>
    <Data>2048</Data>
    <Data>
    </Data>
  </EventData>
</Event>
________________________________
Log Name:      Application
Source:        Application Error
Date:          13.07.2017 11:12:34
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      dgi-admkli-11.AD.DGI.NO
Description:
Faulting application name: ExportPermissionsTool.exe, version: 1.0.0.0, time stamp: 0x586e36ef
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x57366075
Exception code: 0xe0434352
Fault offset: 0x0000000000008a5c
Faulting process id: 0x1184
Faulting application start time: 0x01d2fbaf40e7c879
Faulting application path: C:\Users\thostr\Downloads\ExportPermissionsTool.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 67dd7b44-67ab-11e7-832f-0050568a6e8b
Faulting package full name:
Faulting package-relative application ID:
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-07-13T09:12:34.000000000Z" />
    <EventRecordID>23981</EventRecordID>
    <Channel>Application</Channel>
    <Computer>dgi-admkli-11.AD.DGI.NO</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ExportPermissionsTool.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>586e36ef</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.18340</Data>
    <Data>57366075</Data>
    <Data>e0434352</Data>
    <Data>0000000000008a5c</Data>
    <Data>1184</Data>
    <Data>01d2fbaf40e7c879</Data>
    <Data>C:\Users\thostr\Downloads\ExportPermissionsTool.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>67dd7b44-67ab-11e7-832f-0050568a6e8b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
________________________________
Log Name:      Application
Source:        .NET Runtime
Date:          13.07.2017 11:12:33
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      dgi-admkli-11.AD.DGI.NO
Description:
Application: ExportPermissionsTool.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at CPP_GetGroupMembershipWFP.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-07-13T09:12:33.000000000Z" />
    <EventRecordID>23980</EventRecordID>
    <Channel>Application</Channel>
    <Computer>dgi-admkli-11.AD.DGI.NO</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ExportPermissionsTool.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;ThrowAsync&gt;b__4(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run()
   at CPP_GetGroupMembershipWFP.App.Main()
</Data>
  </EventData>
</Event>

Med vänlig hälsning / Best regards / S pozdravem,

Thomas Strömgren, Workspace Services
Tieto Sweden AB

email thomas.stromgren@tieto.com<mailto:thomas.stromgren@tieto.com>
direct +46 (0)10 48 10 206
mobile +46 (0)70 209 8079
[https://intra2.tieto.com/Inside-Tieto/Sales--Marketing-Corner/Tieto-brand/Brand-Guidelines-and-Templates/Tieto-logo-for-Email-Signature/Tieto_logo_for_email_signature_127x50.png]

Please note: The information contained in this message may be legally privileged, confidential and protected from disclosure.

Från: Vincenzo Sciarra MS [mailto:notifications@github.com]
Skickat: den 7 juli 2017 16:08
Till: Microsoft/emat <emat@noreply.github.com>
Kopia: Stromgren Thomas <Thomas.Stromgren@tieto.com>; Author <author@noreply.github.com>
Ämne: Re: [Microsoft/emat] Program crash (#3)


Export Tool (.exe) is still under development. Use the powershell script instead that works for sure.

Just for debugging purpose can you please also send the exception running the tool from a command prompt?

Thanks

**Comment by elpinnen** [comment]
Ok, now I have successfully run script instead of executable and also CalculateExchangeDelegation (with CsvHelper.dll) but I don’t understand how to use output files? First time I realize that 2 service accounts (one without mailbox) has full access to all mailboxes, so I then rerun with blacklist.csv like this (without any “ around entry’s):

Identity
ad\srv_inet
ad\srv_trio
srv_trio@DGI.NO

But I can’t see any differs in output except another number (same for all rows) at end in output.csv like this:

patrik.andersson@dgi.no,12165


Med vänlig hälsning / Best regards / S pozdravem,

Thomas Strömgren, Workspace Services
Tieto Sweden AB

email thomas.stromgren@tieto.com<mailto:thomas.stromgren@tieto.com>
direct +46 (0)10 48 10 206
mobile +46 (0)70 209 8079
[https://intra2.tieto.com/Inside-Tieto/Sales--Marketing-Corner/Tieto-brand/Brand-Guidelines-and-Templates/Tieto-logo-for-Email-Signature/Tieto_logo_for_email_signature_127x50.png]

Please note: The information contained in this message may be legally privileged, confidential and protected from disclosure.

Från: Vincenzo Sciarra MS [mailto:notifications@github.com]
Skickat: den 7 juli 2017 16:08
Till: Microsoft/emat <emat@noreply.github.com>
Kopia: Stromgren Thomas <Thomas.Stromgren@tieto.com>; Author <author@noreply.github.com>
Ämne: Re: [Microsoft/emat] Program crash (#3)


Export Tool (.exe) is still under development. Use the powershell script instead that works for sure.

Just for debugging purpose can you please also send the exception running the tool from a command prompt?

Thanks

**Comment by reikor0x** [comment]
In the output "-1" means that the users do not have any relationship. When a user have a group number > 0, this means that the user have relationships with other mailbox inside the same group number.

**Comment by reikor0x** [comment]
ExportTool will be retired for version 3 and will re-enter in version 4
